### PR TITLE
Shorten context

### PR DESCRIPTION
**Pull request by acka47**
I didn't make it all the way through. The property list is shortened but not the classes. @dr0i, please use this version for indexing anyway.

### CODE REVIEW

**Comment by acka47** [comment]
I now also managed to shorten the class list. have a nice weekend.

**Comment by dr0i** [comment]
thx u2 :)

**Comment by acka47** [comment]
Looking at the full index, I see that there are some properties not compacted. Will adjust the context accordingly.

**Comment by acka47** [comment]
I guess it is ok for now. We have to re-index it then. I don't intend to do any more work on this  (a few errors will be good for demonstration anyway) so this will be the last indexing round.

**Comment by dr0i** [comment]
New index has been created fine. Merging and closing.

**Pull request merged**
